### ISSUE TITLE
TA feedback (comment storyboard, mockup, and user interface)

### ISSUE THREAD

**Issue by jackykc** [CMPUT301W17T20/Harambe#16]

**Comment by bhinse** [comment]
![moodly_mockup](https://cloud.githubusercontent.com/assets/25091925/23843781/d68215dc-0783-11e7-9e96-a715225f484b.png)
I went to commit the moodly mock up but Melvin has gone through that and treated it like a storyboard. Not sure whats up. but the mockup should of just been labeled and the usecase video needed to be commented.
