### ISSUE TITLE
Make Logo

### ISSUE THREAD

**Issue by victormai** [CMPUT301W17T20/Harambe#54]
Make Logo

**Comment by bhinse** [comment]
Already done unless youre not happy with it 
![moodly_logo](https://cloud.githubusercontent.com/assets/25091925/24425101/18e16f5c-13c0-11e7-98f9-4b9f01fd6204.png)

**Comment by jackykc** [comment]
Yea, we are going with the MS Paint will the word Moodly under the salt

**Comment by jackykc** [comment]
and no, I don't see how this one is related to the app other than the word Moodly.

**Comment by bhinse** [comment]
I'm sorry you feel that way. I chose the color palette base on the pyschology of colors and how they relate to emotions. in additon creating eyes in the O that are scowling. 
How does Facebook, twitter, github, slack relate to their product except in text.

going with the salt as a permanent solution is a complete joke. I asked for your input before and you weren't interested in sharing then.

**Comment by victormai** [comment]
This is an area for placing technical issues guys, disagreements can be put on slack. On the topic of the logo, I think a professional-level logo is a good idea. Although there is nothing wrong with the logo you mocked up Brock, I don't believe that the colour scheme fits the colours of the app very well.  If you were willing to modify the logo or perhaps mock-up another one to the same degree of polish, it would be appreciated.
