### ISSUE TITLE
Get a set of emojis

### ISSUE THREAD

**Issue by jackykc** [CMPUT301W17T20/Harambe#8]

**Comment by hatuongminh96** [comment]
Guys check if these are okay
https://drive.google.com/drive/folders/0B3oB8ZutVPl7bjY0Q2ZSZW0yVUk?usp=sharing

**Comment by victormai** [comment]
I think they're a bit too emotive for the style of our app. Where'd you find them?

**Comment by victormai** [comment]
I compiled some Emojis from EmojiOne here: https://drive.google.com/open?id=0B4HHpl1UT7h_NHhlMG1XZUx4QnM
Since they have an open license, we're clear to use them with a brief mention and since they are pretty popular, they are recognizable. Thoughts?

**Comment by victormai** [comment]
Done and Implemented
